# Generated by Django 3.1.3 on 2020-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_customer_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description not available', max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(default='maindish', max_length=100),
        ),
    ]
