# Generated by Django 3.1.3 on 2020-12-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201218_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
